# Generated by Django 5.2.13 on 2026-04-29 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('pilots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analysis_failed', 'Analysis Failed'), ('draft', 'Draft'), ('finalized', 'Finalized')], default='uploaded', max_length=32)),
                ('source_file', models.FileField(upload_to='logs/%Y/%m/%d/')),
                ('source_original_name', models.CharField(blank=True, max_length=255)),
                ('source_log_type', models.CharField(blank=True, max_length=16)),
                ('vehicle_type', models.CharField(default='ArduPilot Copter', max_length=128)),
                ('flight_date', models.DateField(blank=True, null=True)),
                ('takeoff_at_utc', models.DateTimeField(blank=True, null=True)),
                ('landing_at_utc', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('takeoff_lat', models.FloatField(blank=True, null=True)),
                ('takeoff_lng', models.FloatField(blank=True, null=True)),
                ('takeoff_address', models.CharField(blank=True, max_length=512)),
                ('landing_lat', models.FloatField(blank=True, null=True)),
                ('landing_lng', models.FloatField(blank=True, null=True)),
                ('landing_address', models.CharField(blank=True, max_length=512)),
                ('purpose', models.TextField(blank=True)),
                ('special_flight_types', models.TextField(blank=True)),
                ('route_summary', models.TextField(blank=True)),
                ('official_weather', models.CharField(blank=True, max_length=255)),
                ('official_temperature_c', models.FloatField(blank=True, null=True)),
                ('official_wind_speed_mps', models.FloatField(blank=True, null=True)),
                ('reference_weather', models.CharField(blank=True, max_length=255)),
                ('reference_temperature_c', models.FloatField(blank=True, null=True)),
                ('reference_wind_speed_mps', models.FloatField(blank=True, null=True)),
                ('reference_station_name', models.CharField(blank=True, max_length=255)),
                ('reference_station_distance_km', models.FloatField(blank=True, null=True)),
                ('reference_observed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_source', models.CharField(blank=True, max_length=255)),
                ('safety_notes', models.TextField(blank=True)),
                ('article_notes', models.TextField(blank=True)),
                ('diagnostic_grade', models.CharField(blank=True, choices=[('normal', 'Normal'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=16)),
                ('review_required', models.BooleanField(default=False)),
                ('analysis_error', models.TextField(blank=True)),
                ('aircraft_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_snapshot', models.JSONField(blank=True, default=dict)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_records', to='aircraft.aircraft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_records', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_records', to='pilots.pilot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FlightModeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=128)),
                ('start_at_utc', models.DateTimeField(blank=True, null=True)),
                ('end_at_utc', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_spans', to='flight_records.flightrecord')),
            ],
            options={
                'ordering': ['start_at_utc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlightAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_at_utc', models.DateTimeField(blank=True, null=True)),
                ('disarm_at_utc', models.DateTimeField(blank=True, null=True)),
                ('takeoff_detected_by', models.CharField(blank=True, max_length=64)),
                ('landing_detected_by', models.CharField(blank=True, max_length=64)),
                ('max_altitude_m', models.FloatField(blank=True, null=True)),
                ('max_speed_mps', models.FloatField(blank=True, null=True)),
                ('max_distance_m', models.FloatField(blank=True, null=True)),
                ('battery_start_voltage', models.FloatField(blank=True, null=True)),
                ('battery_end_voltage', models.FloatField(blank=True, null=True)),
                ('battery_min_voltage', models.FloatField(blank=True, null=True)),
                ('battery_max_current', models.FloatField(blank=True, null=True)),
                ('battery_consumed_mah', models.FloatField(blank=True, null=True)),
                ('gps_min_satellites', models.IntegerField(blank=True, null=True)),
                ('gps_max_hdop', models.FloatField(blank=True, null=True)),
                ('ekf_summary', models.TextField(blank=True)),
                ('vibration_summary', models.TextField(blank=True)),
                ('failsafe_events', models.JSONField(blank=True, default=list)),
                ('warning_messages', models.JSONField(blank=True, default=list)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='flight_records.flightrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('flight_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='flight_records.flightrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightTimeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_time_entries', to='aircraft.aircraft')),
                ('flight_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_time_ledger', to='flight_records.flightrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF')], max_length=32)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('flight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to='flight_records.flightrecord')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
