# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrecord",
            name="pilot_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
