# Generated by Django 5.2.13 on 2026-05-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aircraft",
            old_name="remote_id",
            new_name="registration_number",
        ),
    ]
