# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0002_rename_remote_id_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="is_certified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="remote_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
